### ISSUE TITLE
Desklet Bug: Yahoo Finance Quotes disappeared after shutdown

### ISSUE THREAD

**Issue by arax-1238** [linuxmint/cinnamon-spices-desklets#1073]
### Desklet version/Build date

0.9.0 - August 28, 2023

### Cinnamon version

6.0.4

### Distribution

Mint 21.3

### Graphics hardware *and* driver used

Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller

### Desklet name and maintainer

yfquotes@thegli @thegli

### What happened?

I installed Yahoo Finance Quotes desklet and it woks, but when I shutdown and restart the pc the **desklet disappears**.
So I have to install it again. So after every restart.

**Comment by thegli** [comment]
Hi @arax-1238 
Sorry to hear that the desklet doesn't work properly on your machine. Although I cannot reproduce the problem on mine, there are some things we can check:

1. Is this the only desklet that is affected by this problem?
2. After a restart, is your internet connection automatically established and immediately available? Or do you enable it manually some time after login?
3. Do you use a VPN?
4. Do you mean with "_have to install it again_" that you need to add it to the desktop again, or that you even need to download it over and over again?
5. Check the log. To do that, press "Alt-F2", then type "lg" into the command box and hit "Enter" to open the Melange debugger. On the "Log" tab, you find log output from Cinnamon components. Look for the following two entries:
info t=2024-02-24T00:03:51Z Loaded desklet yfquotes@thegli in 5 ms
info t=2024-02-24T00:03:52Z yfquotes@thegli - Successfully retrieved all authorization parameters.
Do you see such entries after a restart, when the desklet does not show up on the desktop?
6. Does the desklet even disappear with default settings? If you changed some settings, can you try with just the default values for once?

Let me know :crossed_fingers:

**Comment by arax-1238** [comment]
Thanks for the quick response!
1. Other desklets work on the same desktop
2. After the restart the Internet connection is automatically established and immediately available
3. no VPN
4. I need to add it back to the desktop
5.6. using all default settings (including actions) I see the two entries in the registry. **BUT** if I choose my stocks (no other changes in default settings) and then restart the PC, I see in the registry that the applet is "loaded" but is missing "retrieved all permission parameters"

**It would appear that my changes to the standard settings prevents their subsequent loading.**
I upload my Log file (created by desklet with my stocks and settings) and personal setting file.
[log with personal settings.txt](https://github.com/linuxmint/cinnamon-spices-desklets/files/14450034/log.with.personal.settings.txt)
[export_yahoo_finanza.json](https://github.com/linuxmint/cinnamon-spices-desklets/files/14450036/export_yahoo_finanza.json)

**Comment by thegli** [comment]
Ciao @arax-1238 

Thank you for the files. With them I could immediately reproduce the problem.

The solution: You need to (re-)enable the option "Send custom User-Agent header" located on the first screen of the settings. That's it :smile:

Background info: This option needs to be active because the EU is one of the regions where the use of cookies is regulated (know as "Cookie Law"). The desklet needs to perform the necessary steps on startup in order to fetch financial information afterwards. For some reason, this process works best when a familiar User-Agent header is sent. Without it, the process gets stuck, and then it's not possible to retrieve any financial data.

That being said - I hope you're still with me :wink:  - the desklet should still load, and display an error message instead. I have to look into this in more detail why that didn't happen.

So, thank you for finding this bug. I hope that the desklet now works for you as expected.

**Comment by arax-1238** [comment]
Thank you, you are very attentive!
With your suggestion the applet works, but after the next restart it gives me an error (I attach the screenshot and log). Another reboot works again, but after another reboot same error again.

It almost looks like a switch that stays in the wrong position and causes a 401 error....
Desklet never worked with my settings before, now in 50% of cases, we are on the right track.... ;-)..
[log with 401 error.txt](https://github.com/linuxmint/cinnamon-spices-desklets/files/14458789/log.with.401.error.txt)
![error 401](https://github.com/linuxmint/cinnamon-spices-desklets/assets/88095527/6c1e5ebb-e8cf-4481-9c4b-ec27957504c3)

**Comment by thegli** [comment]
A pity that it doesn't work 100% :frowning: 
Unfortunately I couldn't reproduce the new problem. The desklet always loaded properly with your configuration after several restarts.
Normally this 401 error occurs when the cookie consent process fails. But the URL in the log looks OK.
Since the authorization data are not stored but fetched anew after every login, I can't explain this "works/doesn't work" behavior.

Sorry, but for the moment I can't provide any more help. So far, you are the first reporting this problem.
Maybe there are some ongoing changes at Yahoo. Let's see if others will also encounter this issue.

**Comment by arax-1238** [comment]
After a further week of use I can say that the desklet is practically perfect: I once received a 401 error which I quickly remedied by restarting Cinammon!
Thank you very much for your help and ...for the great work! :-)
