### ISSUE TITLE
simple-system-monitor@ariel: Always displays Temperature 27.8 °C

### ISSUE THREAD

**Issue by Bleuzen** [linuxmint/cinnamon-spices-desklets#120]
... I already did some tests myself ...
```
/sys/devices/virtual/thermal/thermal_zone0/temp
```
which is used by the desklet always is 27.8.
But it works if I replace thermal_zone0 by thermal_zone2 in metadata.json.
```
{
    "description": "Shows some system status values", 
    "dangerous": true, 
    "uuid": "simple-system-monitor@ariel", 
    "last-edited": 1493402702, 
    "prevent-decorations": false, 
    "thermal-file": "/sys/devices/virtual/thermal/thermal_zone2/temp", 
    "name": "Simple system monitor"
}
```

Please provide a setting for this or detect the right thermal_zone automatically (for example by checking for changes under high cpu usage).

**Comment by NikoKrause** [comment]
@Bleuzen You should mention the author on GitHub by typing @ plus his/her username to trigger a notification and bring his/her attention to an issue or pull request.

You find the username of the author on the cinnamon spices website: spices.linuxmint.com/desklets

**Comment by Bleuzen** [comment]
@arielandrade

**Comment by arielandrade** [comment]
Hello @Bleuzen, as far as I know, the thermal sensor file varys according to the kernel version that you are using, and therefore it's a desklet's setting (that's why you find it in the metadata.json file). 
However, as you correctly point out, a good desklet should allow to change it's settings via GUI, and this one currently doesn't.
So, I'll try to develop a settings manager for the desklet as soon as time permits.

Thank you!

**Comment by Bleuzen** [comment]
Ok ;)
