### ISSUE TITLE
quoteOfTheDay@tinnu: 3.2 or 3.4

### ISSUE THREAD

**Issue by Ilis** [linuxmint/cinnamon-spices-desklets#178]
While I upgrade my Mint to 18.2 and Cinnamon to 3.4 version, I noticed that `stylesheet.css` take effect only from 3.2 folder. It is weird.

**Comment by Ilis** [comment]
@JessW

**Comment by JessW** [comment]
Hi @Ilis , are you saying the issue is that a `stylesheet.css` in QoTD's 3.4 folder doesn't work?

I don't think a 3.4 folder should have been automatically created, was there one?  My understanding is that there will not be a folder for each release of Cinnamon unless there needs to be.  So since the same version of QoTD works for 3.2 and 3.4 (but not 3.0 and earlier), there is only a 3.2 folder, not a 3.4.  Does that make sense?

**Comment by Ilis** [comment]
Hi, @JessW 

I have 2 `stylesheet.css` in my `.local/share/cinnamon/desklets/quoteOfTheDay@tinnu/`

- `/stylesheet.css`
- `/3.2/stylesheet.css`

I've made changes (add font-family) in `/stylesheet.css`, with no effects. I decided to open issue, but first tried to make changes to `/3.2/stylesheet.css`, ant it works.

So, I don't understand why I have to use `/3.2/stylesheet.css`, when I have 3.4 cinnamon version.

**Comment by JessW** [comment]
I see what you're saying, @Ilis .  The way that the xlet versioning works in Cinnamon is that versions 3.2 **and greater** use the 3.2 folder, while versions less than 3.2 use the folder with no version number.  I agree that it can be confusing, and I can add some information about which `stylesheet.css` to change to the README, but otherwise I don't think this is an issue.

**Comment by Ilis** [comment]
> I agree that it can be confusing, and I can add some information about which stylesheet.css to change to the README, but otherwise I don't think this is an issue.

Oh... It is really confusing :)

But it is better to make option for font selection in preferences dialog, then instruction about weird versioning.

I'll close this issue.

**Comment by NikoKrause** [comment]
Since both stylesheets are the same, you can make one of them to be a symbolic link to the other one.
