### ISSUE TITLE
Can't authenticate when first installing desklet - googleCalendar@javahelps.com

### ISSUE THREAD

**Issue by mateusscheper** [linuxmint/cinnamon-spices-desklets#509]
```
 * Desklet version: Default Google Calendar's desklet from Mint - last modified 04/02/2020
 * Cinnamon version: 4.2.4
 * Distribution: Mint 19.2 Cinnamon
 * Graphics hardware: GeForce MX150
 * Driver: xserver-xorg-video-nouveau ver 1.0.15-2

I just installed Google Calendar's desklet and got this when clicking the plus button to add the desklet:

> The "Sign in with Google" option is temporarily disabled for this app
> This app has not yet been verified by Google to use Google Login.

I'm following these steps and got the error in step 3:
https://cinnamon-spices.linuxmint.com/desklets/view/35

**Comment by FantaMagier** [comment]
same problem

**Comment by bit1sam** [comment]
Yeah the same issue here, it sent a verification email I verify said email then try again and still no luck. Is it possible it may be the security setting in Gmail preventing it from allowing?

**Comment by bit1sam** [comment]
Am i the only one dealing with this error "Failed to start a local webserver listening on either port 8080 or port 8090. Please check your firewall settings and locally running programs that may be blocking or using those ports." i figured it might be normal

**Comment by slgobinath** [comment]
This happens because Google is verifying the application for months. The process started last year September and still its under review. Don't panic there is no security violations. The long story in short:
When you authenticate the desklet to access your Google Calendar, Google provides a token. The token is saved on your computer and only used by the desklet (not shared with me or any third parties). However, Google only had two categories for apps using their APIs:
1. Internal application (don't remember the exact name but means within an organization)
2. Web service

I think in these cases, the developer may store the token. However this desklet does not fall under both of these categories and I guess which made the process complex. While the app is under review, Google does not allow new users to authenticate.


The same problem happened to the famous tool `gcalcli` too and they do discuss on some workarounds here: https://github.com/insanum/gcalcli/issues/497

I have written a medium post explaining how to create your own token: https://medium.com/@lgobinath/how-to-use-google-calendar-desklet-41d8aa0dbedd but it requires you to create your own Google App.

The following trick also worked for me:
When you get the "app isn't verified" page, click advanced and "Go to Personal Calendar Desklet". Then allow the desklet to access your calendar.
![cinnamon_calendar](https://user-images.githubusercontent.com/4003168/83875011-62f2ab80-a704-11ea-9543-274529b92fe9.png)
