### ISSUE TITLE
diskspace@schorschii does not calculate percentage properly

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/cinnamon-spices-desklets#625]
Disk Space (diskspace@schorschii)
```
 * Desklet version   Version 1.12 (2021-02-06 11:15:34)
 * Cinnamon version Cinnamon 4.8.6 
 * Distribution - Linux Mint Cinnamon 64bit
 * Graphics hardware * Intel UHD Graphics 620 driver: i915 v: kernel
```
@schorschii 

**Issue**
Disk space percentage calculation seems to be off.

See screen shot.   Calculator computes it as 25.07 %  and display is 26%.   That's a pretty heavy round up.

![Disk-Space](https://user-images.githubusercontent.com/26556059/110212963-dd0ab900-7e6b-11eb-8254-55a87e287706.png)

**Comment by schorschii** [comment]
Unfortunately, its not that easy. The desklet displays the percentage output from `df` directly on the screen. The "used" and "available" space values are also obtained from `df` but of course have to be rounded, because nobody wants to see the size in bytes. So the inaccurate value is not the percentage, but the free/total size, which causes the divergence.

Your `df` output in the moment of the screenshot would be interesting to see.

**Comment by ChooChooAl** [comment]
/dev/nvme0n1p6 104254288  24874772  74040588  26% /

I'm currently using 25.5 (not the 25.4) but even still that calculates to 0.251727542 and rounding down to 25 %    So yes, it is df that's creating the issue.

I would consider this closed.  It's not worth trying to get that exact.  I can 25.5 gig and then 26.5 gig and realize I've picked up a gig of something.   Percentage is less important.
Thanks.
