### ISSUE TITLE
Weather Desklet (bbcwx@oak-wood.co.uk) - Error 202

### ISSUE THREAD

**Issue by pzxyk8** [linuxmint/cinnamon-spices-desklets#636]
```
Desklet version/Build date: Version 2.10 (2021-03-23 10:52:16)
System:    Kernel: 5.4.0-67-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.8.6 
           wm: muffin dm: LightDM Distro: Linux Mint 20.1 Ulyssa base: Ubuntu 20.04 focal 
Graphics:  Device-1: VMware SVGA II Adapter driver: vmwgfx v: 2.15.0.0 bus ID: 00:02.0 
           chip ID: 15ad:0405 
           Display: x11 server: X.Org 1.20.9 driver: vmware unloaded: fbdev,modesetting,vesa 
           resolution: 1366x768~60Hz 
           OpenGL: renderer: SVGA3D; build v: 2.1 Mesa 20.2.6 direct render: Yes 

 ```

**Notify author of desklet**
@tipichris 

**Issue**
Error 202 is displayed. No icons and no forecasts are available.

**Steps to reproduce**

**Expected behaviour**

**Other information**
"BBC" data service, 3172394 location code

**Comment by tipichris** [comment]
That code just reflects what the provider is returning. It's not at issue with the desklet.
And in the couple of minutes since I started looking at this https://weather-broker-cdn.api.bbci.co.uk/en/forecast/rss/3day/3172394 has started returning the expected RSS. So it's working now :)
![image](https://user-images.githubusercontent.com/89666/112281551-1326a600-8c7e-11eb-97b8-4d93ba7cb060.png)
