### ISSUE TITLE
bbcwx@oak-wood.co.uk : Add weather.gov API as data source

### ISSUE THREAD

**Issue by gwillgues** [linuxmint/cinnamon-spices-desklets#752]
This desklet has not received any new data sources for a while. I have come across api.weather.gov which looks like a promising addition

I believe the weather.gov API would be a very useful and potentially more reliable long term (less likely to get shut down as it is a government provided service) addition to this desklet for US based users. 

Currently as long as the request contains a user agent string there is no API key or sign-up process required. They have stated in the documentation the user-agent approach may be replaced by an API key at a later date. 

The API supports plugging in a latitude and longitude and getting weather results for that specified area. In addition, the API supports pulling weather data directly from certain observation stations, such as airports or other locations, and it supports pulling lists of the closest observation stations to a lat/long pair. So there are a lot of nice features that could be used, including weather alerts published by the NOAA.

I may end up working on this myself when I have time, but my current knowledge of JS is limited, but I wanted to request this if anyone else thinks its a good idea.

For more information on the weather.gov API see https://www.weather.gov/documentation/services-web-api

**Comment by rcalixte** [comment]
I'm working on a refactor of this desklet and I'm going to try to include as many of the features from the weather.gov API as possible. I can't commit to a timeline but I'm going to try for sooner than later. Some of the features you've mentioned would require a bit more implementation in the desklet itself since it doesn't currently have features or settings for alerts and whatnot. Not a bad idea for a future feature set though.
