### ISSUE TITLE
yfquotes@thegli  Error: Yahoo Finance service not available!

### ISSUE THREAD

**Issue by David-DeZ** [linuxmint/cinnamon-spices-desklets#840]
Version 0.8.2 (2023-03-31 12:27:54)
Linux Mint 21.1 Cinnamon

Noticed  this morning (20/4/23) that it is blank not listing my stocks but with, in red, "Error: Yahoo Finance service not available!". Yahoo Finance via the web (https://finance.yahoo.com/portfolios) does work, however they have introduced a beta test. Also yesterday updated Linux Kernal to 5.15.0-70 from 5.15.0-69.  Firefox & Chromium were also updated.
**Notify author of desklet**

**Comment by David-DeZ** [comment]
As quickly as the problem came up, it has now disappeared - however I won't close it yet in case it reappears on a daily basis -  perhaps it is based on when the market is open or closed - the market is now open and it's fine, this morning (GMT+3) when it was closed the problem existed. 

I will close this issue after a few days if all continues well.

**Comment by thegli** [comment]
The problem we encountered a few weeks ago unfortunately reappeared. AFAIK it has nothing to do with the market opening period, but with a technical change Yahoo did on their side. So far I'm still optimistic that they again will resolve the issue shortly.

BTW, the problem is _not_ related to Linux Mint or Cinnamon.

**Comment by thegli** [comment]
Created PR #843 which allows to switch between API versions

**Comment by David-DeZ** [comment]
Thanks Thomas!

**Comment by David-DeZ** [comment]
Thanks so much, Thomas!

Any idea when the change will be distributed via Linux Mint? 

Much appreciated!

**Comment by thegli** [comment]
That I cannot say. The PR is now in the hands of the repo maintainers, like @brownsr

In the meantime, you can patch the desklet code yourself. The small procedure (a single command + restart) is documented in the [desklet's comment section](https://cinnamon-spices.linuxmint.com/desklets/view/42).

**Comment by teto90** [comment]
Great Job as ever!

Thanks, I was experiencing the same problem!

**Comment by David-DeZ** [comment]
Sorry to report that the problem has returned - May 24 05:20 GMT
I redid the terminal command and restarted Cinnamon but this time it didn't work.

**Comment by thegli** [comment]
PR #853 should take care of this (for V7 only - no fix for V6)

**Comment by David-DeZ** [comment]
Thanks!  Any "guesstimate" when it might be available?

**Comment by thegli** [comment]
Your guess would be as good as mine :smile:
Based on the queuing PRs, we might be looking at weeks rather than days...

If you don't mind a manual installation: I prepared a release on my personal page: https://github.com/thegli/yfquotes-cinnamon-desklet. But in general, I recommend to wait for the official release.

**Comment by David-DeZ** [comment]
Thanks Thomas! I'll follow your advice and wait for the official release - I can "suffer" having the empty box on my desktop until then, and there are other ways I can monitor my invested "millions" (wish it were so!).

**Comment by David-DeZ** [comment]
Was just now updated on my computer 30/6/23 - 11:25 (GMT+3). 

It works!   THANKS THOMAS!

Will wait a week or so before closing this issue to make sure it's stable.

**Comment by thegli** [comment]
Thank you for your quick feedback.
Now proper monitoring of all the invested "millions" is possible again :moneybag:  :smile:

**Comment by David-DeZ** [comment]
I upgraded to 21.2 yesterday - today a new version came and back to the same problem!!!    Sorry, Thomas!

**Comment by thegli** [comment]
The new version got a brand-new config setting which should remedy the current problem situation:

1. Open the settings dialog (right-click on desklet, then select "Configure...")
2. Enable the new option "Send custom User-Agent header" (right at the bottom of the first tab)
3. Leave the default value, and close the settings dialog.

And that should do the trick :sunglasses:

**Comment by David-DeZ** [comment]
Thank you Rick!  Thank you Thomas!  Works now

**Comment by David-DeZ** [comment]
Thank you Rick! Thank you Thomas! Works now.
I'm a happy camper once again tracking my "millions" (Ha Ha).

Purely out of curiosity - no need to reply:
Are there users who do not require the header to be sent? Based on your answer, could it be defaulted to being enabled as other potential users may give up if it doesn't initially work for them? Can other user-agent headers be used (eg Chromium) or is Firefox defaulted as being included in Linux Mint all users have it?

Hopefully no future need to reopen the issue - but if so I know that the desklet is in good hands!

Thanks again!!

**Comment by thegli** [comment]
Hi David

Glad you asked :grin:
The recent problem is caused by a temporarily unavailable web resource that the desklet retrieves once at startup.
Technically, the Yahoo server responds with an HTTP status 429 "Too Many Requests" during these high-load periods.
IF we were all patient folk, we could simply wait when there is less load on the server, but well...

By setting the User-Agent header to a(ny) value of a popular browser, the desklet's request gets - somehow, I'm not really clear on this - prioritized, and is not rejected anymore.
And yes, we could send User-Agent values from other browsers. As long as the default value of the desklet works, there's no real need to change it, though.

I'm undecided if this setting should be enabled by default, as the desklet worked for years without this little "deception". Let's see how it goes.

**Comment by David-DeZ** [comment]
Thanks for the detailed explanation, Thomas. I even understood it!

For what it's worth my vote is to make the option of sending the user-agent header to default as enabled - otherwise users will, like I myself did, not know to enable it if the desklet doesn't work, and unlike myself, may give up on installing the desklet. No need to turn off potential new users, or lose old ones.

I see your point that " ... the desklet worked for years without this little "deception" ... " but it doesn't now and who knows when it will again. If it does (ie Yahoo fixes it), will the "deception" cause the desklet to fail? If not, then no harm to make the option to default as enabled - if so, then ... well I leave that to you! Perhaps some instruction on the Configure Screen, such as "toggle this if Yahoo is not responding". 

I also humbly suggest not to show the user-agent header at all on the Configure screen as there is no need or benefit to change it and as Firefox is included in Linux Mint anyway, it is acceptable LM software. It only confuses.

BESTEST
David

PS As you can see from my comments I have a background in Information Technology - mostly technical and managerial from mid-70s through early 90s then mostly marketing until retirement.
