### ISSUE TITLE
diskspace@schorschii - desklet is causing stutter

### ISSUE THREAD

**Issue by H34dl3ss** [linuxmint/cinnamon-spices-desklets#932]
### Desklet version/Build date

Version 1.13 (2023-08-08 04:35:12)

### Cinnamon version

Cinnamon 5.6.8

### Distribution

Linux Mint 21.1 Vera

### Graphics hardware *and* driver used

AMD and Nvidia

### Desklet name and maintainer

diskspace@schorschii @schorschii

### What happened?

I noticed stutter when playing games in windowed mode.
When going fullscreen, the stutter is gone.

I searched for reasons and found a post in the Mint forum that stated desklets could cause the issue.
I can confirm this. An user account without desklets is not suffering of stutter.

Now I went down the rabbit hole and removed all desklets and applets and added one by one until the stutter was back.
This proved to be the diskspace applet. I have multiple drives/partitions monitored and it seems the more desklets are running, the more stutter is happening.

It is very annoying as it affects video playback also. It can be observed even with mangohud glxgears.
I'm glad to support further data if necessary.

**Comment by schorschii** [comment]
Yes, I can reproduce that. It seems to get worse the more desklets are active and I could swear this didn't happen in Mint 20. I tracked it down and the problematic part seems to be the initialization of the Gio subprocess call: `subprocess.init(null);`

An alternative could be to read the information from a file since Gio's `load_contents_async()` function does not produce stuttering. So many information are available in `/sys`, `/proc` and `/run` but unfortunately, I'm unable to find file system free/total space information there.

I don't have a quick solution for this but I'll keep thinking about it.

**Comment by schorschii** [comment]
OK, I think I found a solution. First, the usage of the async subprocess seems wrong. Instead of `subprocess.wait_async()`, I now use `subprocess.communicate_utf8_async()` and `communicate_utf8_finish()` as suggested by the [Gio docs](https://docs.gtk.org/gio/method.Subprocess.communicate_utf8_async.html).

Then, I found out that [Gio provides a function to get file system information](https://docs.gtk.org/gio/vfunc.File.query_filesystem_info_async.html) by itself. No need to execute a `df` subprocess anymore! A much more elegant solution.

@H34dl3ss can you please copy [my adjusted desklet.js](https://github.com/schorschii/cinnamon-spices-desklets/blob/stutter-fix-diskspace/diskspace%40schorschii/files/diskspace%40schorschii/desklet.js) into your `~/.local/share/cinnamon/desklets/diskspace@schorschii`, restart Cinnamon and post a feedback here if the stuttering is gone in the new version? Thanks.

**Comment by claudiux** [comment]
@schorschii That seems OK now. Can you create a PR, please?

**Comment by schorschii** [comment]
@H34dl3ss you can test with version 1.14 from the official repo now. I'd appreciate your feedback.

**Comment by H34dl3ss** [comment]
Yes, I can confirm there is no noticeable stutter during video playback now.
Thank you for taking care of this!
